/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/Addons.js'
import type { Group, Material, MaterialEventMap, Mesh } from 'three'
import { loadPlanetaryData } from '../../hooks/loadSinglePlanet'
import { getOrbitCurve, setPlanetPosition } from '../../functions/orbitData'

interface JupiterGLTF extends GLTF {
    nodes: {
        cubemap: Mesh
    }

    materials: {
        None: Material<MaterialEventMap> | Material<MaterialEventMap>[] | Readonly<Material<MaterialEventMap> | Material<MaterialEventMap>[] | undefined>
    }
    
}

type PlanetProps = JSX.IntrinsicElements['group'] & {
  date: string
}

export function JupiterModel({date, ...props} : PlanetProps) {
    const group = useRef<Group>(null)
  const { nodes, materials } = useGLTF('/jupiter.glb') as unknown as JupiterGLTF

  const {data: jupiterData, loading, error} = loadPlanetaryData("jupiter", date)
  const orbit = getOrbitCurve(jupiterData)
  setPlanetPosition(orbit, group)
  return (
    <group ref = {group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.cubemap.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/jupiter.glb')