/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef, type JSX } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { Mesh, Material, Group, Vector3, CatmullRomCurve3 } from 'three'
import type { GLTF } from 'three/examples/jsm/Addons.js'
import { loadPlanetaryData } from '../../hooks/loadSinglePlanet'
import { getOrbitCurve, setPlanetPosition } from '../../functions/orbitData'

interface MercuryGLTF extends GLTF {
    nodes: {
        Cube008: Mesh
    }

    materials: {
        'Default OBJ.005': Material 
    }
}


export function MercuryModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<Group>(null)
  const { nodes, materials } = useGLTF('/mercury.glb') as unknown as MercuryGLTF
  const { data: mercuryData } = loadPlanetaryData('mercury')

  const orbit = getOrbitCurve(mercuryData)

  setPlanetPosition(orbit, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Default OBJ.005']}
      />
    </group>
  )
}