/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { Group, Material, MaterialEventMap, Mesh } from 'three'
import type { GLTF } from 'three/examples/jsm/Addons.js'
import { getOrbitCurve, setPlanetPosition } from '../../functions/orbitData'
import { loadPlanetaryData } from '../../hooks/loadSinglePlanet'

interface SaturnGLTF extends GLTF {
    nodes: {
        Saturn001: Mesh
        RingsTop: Mesh
        RingsBottom: Mesh
    }

    materials: {
        SaturnRings: Material
        None: Material<MaterialEventMap> | Material<MaterialEventMap>[] | Readonly<Material<MaterialEventMap> | Material<MaterialEventMap>[] | undefined>
    }
}

export function SaturnModel(props: JSX.IntrinsicElements['group']) {
    const group = useRef<Group>(null)
  const { nodes, materials } = useGLTF('/saturn.glb') as unknown as SaturnGLTF

  const {data: saturnData, loading, error} = loadPlanetaryData("saturn")
    const orbit = getOrbitCurve(saturnData)
    setPlanetPosition(orbit, group)
  return (
    <group ref = {group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Saturn001.geometry}
        material={materials.None}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RingsTop.geometry}
        material={materials.SaturnRings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RingsBottom.geometry}
        material={materials.SaturnRings}
      />
    </group>
  )
}

useGLTF.preload('/saturn.glb')