/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { Group, Material, Mesh } from 'three'
import type { GLTF } from 'three/examples/jsm/Addons.js'
import { getOrbitCurve, setPlanetPosition } from '../../functions/orbitData'
import { loadPlanetaryData } from '../../hooks/loadSinglePlanet'

interface UranusGLTF extends GLTF {
    nodes: {
        Uranus: Mesh
    }

    materials:
    {
        'Default OBJ.001': Material
    }
}

export function UranusModel(props: JSX.IntrinsicElements['group']) {
    const group = useRef<Group>(null)
  const { nodes, materials } = useGLTF('/uranus.glb') as unknown as UranusGLTF
  const {data: uranusData, loading, error} = loadPlanetaryData("uranus")

  const orbit = getOrbitCurve(uranusData)
  setPlanetPosition(orbit, group)
  return (
    <group ref = {group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Uranus.geometry}
        material={materials['Default OBJ.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/uranus.glb')